package Singleton;
// Generated 14-nov-2018 9:53:03 by Hibernate Tools 3.5.0.Final

/**
 * Empleados generated by hbm2java
 */
public class Empleados implements java.io.Serializable {

	private String nombre;
	private String apellidos;

	public Empleados() {
	}

	public Empleados(String nombre) {
		this.nombre = nombre;
	}

	public Empleados(String nombre, String apellidos) {
		this.nombre = nombre;
		this.apellidos = apellidos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

}
